name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+[A-Za-z]*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Linux and Windows cross compilers
        run: sudo apt-get install --yes --no-install-recommends musl-tools gcc-mingw-w64-x86-64-win32

      - name: Install Rustup targets
        run: rustup target add x86_64-unknown-linux-musl x86_64-pc-windows-gnu

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: cargo build --verbose --release --target x86_64-unknown-linux-musl --target x86_64-pc-windows-gnu

      - name: Get the release version from the tag
        shell: bash
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build archive
        shell: bash
        run: |
          binary_name="tuisto"

          wintarget="x86_64-pc-windows-gnu"
          linuxtarget="x86_64-unknown-linux-musl"

          windir="$binary_name-${{ env.VERSION }}-$wintarget"
          linuxdir="$binary_name-${{ env.VERSION }}-$linuxtarget"

          mv "target/$wintarget/release/$binary_name.exe" "$windir"
          mv "target/$linuxtarget/release/$binary_name" "$linuxdir"

          7z a "$windir.zip" "$windir"
          echo "WINASSET=$windir.zip" >> $GITHUB_ENV

          tar -czf "$linuxdir.tar.gz" "$linuxdir"
          echo "LINUXASSET=$linuxdir.tar.gz" >> $GITHUB_ENV

      - name: Upload the binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.WINASSET }}
            ${{ env.LINUXASSET }}
